# Generated by Django 4.2.2 on 2023-07-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_movie_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
